spring:
  application:
    name: Task-Sink
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: tasktopic
logging:
  level:
    org.springframework.cloud.task: debug
    org.springframework.cloud.stream: debug
