logging:  level:    root: debug
server:
  port: 0
eureka:
  instance:    instance-id: ${spring.application.name}  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:9999/eureka  
management:  endpoints:    web:      exposure:        include:        - hystrix.stream      
spring:  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest      
      