debug: false
server:
  port: 9003
  servlet:
    context-path: /services
security:
  oauth2:
    client:
      client-id: test
      client-secret: testSecret
      authorized-grant-types:
      - authorization_code
      - refresh_token
      - password
      - client_credentials
      scope:
      - toll_read
      - toll_report
#spring:
#  security:
#    user:
#      name: srini91
#      password: srini
#      roles:
#      - USER