server:
  port: 8888
spring:
  application:
    name: Toll-Config-Server
  profiles:
    active:
    - dev  #if set to native searches the files in local resource folder
  security:
    user:
      name: srini91
      password: test
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: git@git-ssh.web.boeing.com:srinivas.channakeshava/toll-config-files.git
          search-paths:
          - station*
#        encrypt:
#          enabled: false